### ISSUE TITLE
module 'pyhelios' has no attribute 'loggingDefault'

### ISSUE THREAD

**Issue by evagap** [3dgeo-heidelberg/helios#100]
![Screen Shot 2021-11-06 at 6 06 37 PM](https://user-images.githubusercontent.com/33232942/140625112-652af0d8-15c9-42c4-a2e4-16b8e77cba9d.png)

Hello!

After running the instructions for pyhelios, I get the following error:

`module 'pyhelios' has no attribute 'loggingDefault'`

Could you please let me know how to resolve it?
Thank you!

**Comment by han16nah** [comment]
Hi @evagap 
can you send the code that raised this error? From the warning, I assume you forgot the parenthesis. Make sure you use `pyhelios.loggingDefault()` and not `pyhelios.loggingDefault`
If this does not solve your issue, please provide the python code and the HELIOS++ version you are using so we can have a look at our source code. 
Best,
Hannah

**Comment by evagap** [comment]
Hi Hannah, the code that raised this error is `helios.py`

I haven't made any changes to the code. I use the latest version 1.0.9
[Dockerfile log.pdf](https://github.com/3dgeo-heidelberg/helios/files/7493035/Dockerfile.log.pdf)

I also tried installing HELIOS++ with the python bindings using the Dockerfile and I get the attached errors.

Thank you for your help!
Best,
Eva
