### ISSUE TITLE
tiff-Loader from pyhelios not working

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/helios#12]
Loading a tiff-Scenepart from pyhelios throws an error: 
![image](https://user-images.githubusercontent.com/24376088/105717791-d6119200-5f20-11eb-8a88-b22af59f908e.png)

Loading the same survey XML with `helios.exe` works and produces this output:
![image](https://user-images.githubusercontent.com/24376088/105717766-ceea8400-5f20-11eb-8e29-ff01bd1bf181.png)

**Comment by albertoesmp** [comment]
The GDAL drivers were not loaded from pyhelios, thats why ERROR 4 arised. It has been already solved. Please, close the issue once you confirm everything works as expected. Otherwise, please provide me with some demo so I can reproduce further problems.

**Comment by lwiniwar** [comment]
fixed in 422f89d1efecb420bf07f43888bab4dde55845fb
