### ISSUE TITLE
Toyblock test error 

### ISSUE THREAD

**Issue by NanBlanc** [3dgeo-heidelberg/helios#132]
Hi, 
I'm starting to work with Helios++, and as i was trying some of your survey examples, i came across this error for the `data/surveys/toyblocks/als_toyblocks.xml` file : 
```
Scene loaded in 0.014s
Reading Spectral Library...
Using default value for attribute 'seed' : AUTO
Traceback (most recent call last):
  File "pyhelios_demo/helios.py", line 130, in <module>
    scene.gen_from_xml()
  File "/home/stocker_o/travaux/simulation/helios/pyhelios_demo/pyh_obj.py", line 87, in gen_from_xml
    part.apply_tf()
  File "/home/stocker_o/travaux/simulation/helios/pyhelios_demo/pyh_obj.py", line 270, in apply_tf
    self.o3dGeometry.translate(np.array(self.translation.translation, dtype=float), relative=True)
TypeError: translate(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.geometry.Geometry3D, translation: numpy.ndarray[float64[3, 1]], relative: bool = True) -> open3d.cpu.pybind.geometry.Geometry3D

Invoked with: TriangleMesh with 36 points and 12 triangles., array([-1.]); kwargs: relative=True
```

It seems that the line 36 in the file "`data/scenes/toyblocks/toyblocks_scene.xml`" => `<param type="integer" key="onGround" value="-1" />` was causing problems. By removing it, everything seems to work fine.

**Comment by lwiniwar** [comment]
Hi @NanBlanc, 
thank you for reporting the issue. We are preparing the release of a new version, 1.1.0, where the bug has been fixed.
See 79366796446bda9252c4bd073e6092571429fbe4 for the fix.
Best,
Lukas
