### ISSUE TITLE
Dynamic scene confusion

### ISSUE THREAD

**Issue by pryvision** [3dgeo-heidelberg/helios#135]
Using the dev branch head as of 12/14, I am trying to get a scene with dynamic objects working. There does not appear to be any documentation about this feature so maybe I am doing it wrong. 

The first thing I tried was using the moving_tls_toyblocks.xml as a scene.

> python3 helios.py data/surveys/toyblocks/moving_tls_toyblocks.xml

This runs the simulation fine, but from what I can tell the DynScene::doSimStep() is never called and the scene objects are not updated during the course of the simulation. I see there is code to explicitly call this function and some other KdTree magic inside of DynamicSceneDemo, so I build helios with PCL/VTK support so I can run this demo. 

The demo runs, doSimStep() is called and the geometry is updating, however, there doesn't appear to be any LiDAR points being calculated or plotted. 

Am I missing something here? How can I get data from a dynamic scene?

**Comment by albertoesmp** [comment]
Hi @pryvision and thank you for your interest on this topic.
Dynamic scene is something we are working on for the next big Helios++ release. At the moment, it is only possible to debug dynamic scenes to check everything works as expected. However, computing a dynamic simulation is not supported yet. It is something we are planning for the next big release. If you are interested in collaborating with us for development of dynamic scenes we would really appreciate it. Please, contact us via email for further engagement on the project: helios@uni-heidelberg.de
