### ISSUE TITLE
Helios getting stuck building KD-Tree 

### ISSUE THREAD

**Issue by FelixEickeler** [3dgeo-heidelberg/helios#148]
The current dev branch is getting stuck at "Building KD-Tree". There is no cpu or io interaction.
I tested this on ubuntu 20.04 & debian bullseye with the arbaro demo files.  

The problem is elevated as the dev-branch seems to be the default branch for helios.

**Comment by lwiniwar** [comment]
Fixed by reverting the latest commit on `dev`.
