### ISSUE TITLE
efilepath-option for xyzloader

### ISSUE THREAD

**Issue by han16nah** [3dgeo-heidelberg/helios#15]
We have the `efilepath` parameter, which can be used to load multiple files at once, e.g. 

```xml
<part>
    <filter type="objloader">
        <param type="string" key="efilepath" value="data/sceneparts/my_objects/.*.obj" />
    </filter>
</part>
```

loads all OBJ-files in the folder `data/sceneparts/my_objects`.

The `efilepath` option is only available for the `objloader` and `detailedxoxels`. It would be great to make this option available for the `xyzloader` as well.

**Comment by albertoesmp** [comment]
It is possible to use efilepath after today update. Please, check it works as expected and if so, close the issue. Otherwise, please let me know what is going on so I can fix it.
