### ISSUE TITLE
Missing pyhelios properties

### ISSUE THREAD

**Issue by han16nah** [3dgeo-heidelberg/helios#19]
In pyhelios, there are some properties missing for the `leg`:

`scannerSettings`: 

- [x]  `template` (to reuse a scanner settings template defined at the beginning of a survey file)

`platformSettings`: 

- [x]  `yawAtDeparture`

**Comment by albertoesmp** [comment]
This issue has been addressed. Please, verify new behavior is as expected and close the issue. Otherwise, please provide a demo reproducing misbehaviors so they can be fixed.

**Comment by han16nah** [comment]
Both properties are now accessible from pyhelios and work as expected.
