### ISSUE TITLE
Consider "up" parameter of objloader (scene XML) in helios.py

### ISSUE THREAD

**Issue by han16nah** [3dgeo-heidelberg/helios#191]
**The problem**

We have a parameter "up" for the objloader in the scene XML (see recent PR #190), which defined the "up" axis (which e.g., when exporting from blender is the y-axis and not the z-axis).
This parameter is not yet considered in `helios.py`, leading to a wrong display of the scene.

**Solution**

In `helios.py`, read the `up` parameter from the XML and rotate the sceneparts with `open3d` accordingly for displaying them in the live visualization. 

**How to reproduce**
Explain in detail how to reproduce the bug. You can structure the individual steps as a numbered list, like below.

1. Create a scene which uses the "up" parameter, e.g.,
```xml
<?xml version="1.0" encoding="UTF-8"?>
<document>
    <scene id="arbaro_demo" name="Arbaro Demo">
        <part id="0">
            <filter type="objloader">
                <param type="string" key="filepath" value="data/sceneparts/basic/groundplane/groundplane.obj"/>
            </filter>
            <filter type="scale">
                <param type="double" key="scale" value="100" />
            </filter>
        </part>
        <part id="1">
            <filter type="objloader">
                <param type="string" key="filepath" value="data/sceneparts/arbaro/black_tupelo_low.obj"/>
                <param type="string" key="up" value="y" />
            </filter>
            <filter type="translate">
                <param type="vec3" key="offset" value="0;15;0" />
            </filter>
            <filter type="scale">
                <param type="double" key="scale" value="0.5" />
            </filter>
        </part>
        <part id="2">
            <filter type="objloader">
                <param type="string" key="filepath" value="data/sceneparts/arbaro/sassafras_low.obj" />
                <param type="string" key="up" value="y" />
            </filter>
            <filter type="translate">
                <param type="vec3" key="offset" value="-10;15;0" />
            </filter>
            <filter type="scale">
                <param type="double" key="scale" value="0.5" />
            </filter>
        </part>
    </scene>
</document>
```
(arbaro demo)

2. Execute the survey with helios.py, e.g., 
```
python run\helios.py data\surveys\demo\tls_arbaro_demo.xml --lasOutput --rebuildScene --zipOutput
```
3. Notice that the tree objects are lying sideways and do not match the simulated points.

**Expected behavior**

If `<param type="string" key="up" value="y" />` is used within the `objloader ` filter for a scenepart, this scenepart should be rotated around the x-axis by 90 degrees.

**Actual behavior**

Currently, no rotation is performed, when `<param type="string" key="up" value="y" />` is used for a scenepart.

**Comment by mark-searle99** [comment]
Should be fixed as of [pull request no 239](https://github.com/3dgeo-heidelberg/helios/pull/239).
