### ISSUE TITLE
Warning Message: "Leg is too short to achieve the desired (movePerSec_m) speed."

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/helios#193]
The warning message "Leg is too short to achieve the desired (movePerSec_m) speed." appears not only for the `multicopter` type, but also for the `linearpath` platform - although it is not applicable there.

I suggest to suppress printing this message unless the platform is of `multicopter` type.

**Comment by miguelyermo-heidelberg** [comment]
Fixed in #200. Feel free to test the fix before closing the issue.
