### ISSUE TITLE
Broken las output with stripId and --las10 flag.

### ISSUE THREAD

**Issue by mark-searle99** [3dgeo-heidelberg/helios#196]
**The problem**
When specifying las 1.0 output for surveys with stripIds as added in this [issue](https://github.com/3dgeo-heidelberg/helios/issues/143) using only the command `--las10`, the output comes out broken. To get a proper result the `--lasOutput` flag has to be set **additionally**.

**How to reproduce**
Run a survey with stripIds twice, once with only `--las10` flag and once with both `--las10` and `--lasOutput` flag as so:

`run\helios data/surveys/survey_with_stripid.xml --las10` -> broken las file

`run\helios data/surveys/survey_with_stripid.xml --las10 --lasOutput` -> working las file

**Expected behavior**
Only the `--las10` flag should be needed to produce working las 1.0 output.

**Actual behavior**
Both the  `--las10` and `--lasOutput` flags are needed.

This issue is occuring on the current version of the dev branch.

**Comment by miguelyermo-heidelberg** [comment]
Fixed in #198. Tested with different options, including --zipOutput. As soon as you can confirm that is working fine, the issue can be closed.
