### ISSUE TITLE
New scanner parameter "maxNumberOfReturnsPerPulse"

### ISSUE THREAD

**Issue by han16nah** [3dgeo-heidelberg/helios#20]
Laser scanners are often limited in the number of returns that can be recorded per pulse.
We should introduce a new parameter `maxNumberOfReturnsPerPulse` or `maxNOR`, which is defined in the _scanner.xml_.

For instance, to simulate a single-return sensor (maxNOR = 1), only the first return should be kept in the output point cloud. Note that both the Return Number and the (total) Number of Returns have to be adapted in the output point cloud. The default of the new parameter should be to not limit the number of returns per pulse (as is currently the case).

**Comment by albertoesmp** [comment]
The maxNOR parameter has been implemented. An example can be found at scanner_tls.xml. Please, do a few tests with different configurations to validate implementation before closing this issue.
