### ISSUE TITLE
Missing error messages if xyzloader file not found

### ISSUE THREAD

**Issue by han16nah** [3dgeo-heidelberg/helios#21]
**Problem:**
If a `filepath` that does not exist is provided in the scene XML file in the `objloader`, `geotiffloader` or `detailedvoxels` an error is raised and the survey aborts.
```
Applying filter: objloader
Reading 3D model from .obj file 'data/sceneparts/bla.obj'...
File not found: data/sceneparts/bla.obj
```

```
Applying filter: geotiffloader
Reading 3D model from GeoTiff file 'data/sceneparts/tiff/bla.tif'...
ERROR 4: data/sceneparts/tiff/bla.tif: No such file or directory
```

```
Applying filter: detailedvoxels
Reading detailed voxels from data/sceneparts/syssifoss/bla.vox
Voxel file not found: data/sceneparts/syssifoss/bla.vox
```

If a not-existing `filepath` is defined for the `xyzloader`, no error is raised and the scene is built normally (but with 0 voxels from the non-existent file).

```
Applying filter: xyzloader
Reading point cloud from XYZ file data/sceneparts/bla.xyz ...
Adding default material
Point cloud file read successful (0 voxels)
```

**Task**:
For the `xyzloader`, raise an error and abort the simulation if the file is not found (just like for the other loaders).

**Comment by albertoesmp** [comment]
This issue has been fixed on commit: https://github.com/3dgeo-heidelberg/helios/commit/bf1b80028107822d8489fe6a02c7307a569ff114

Please, check it is working as expected. If so, close the issue, otherwise just let me know.
