### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mgonzalezstefane** [3dgeo-heidelberg/helios#235]
Hi, 

I am getting this error when I try to run the ALS file. It is related to the width and height of the window. 

![Untitled picture](https://user-images.githubusercontent.com/106116117/169899856-90234a8f-8339-4e3a-adc2-aa5e4d4c678c.png)

**Comment by mgonzalezstefane** [comment]
Hi, 

I am using Helios ++ at the moment. It looks right on the 3D view scene. 
I think that I am writing it correctly.

**Comment by lwiniwar** [comment]
Hi @mgonzalezstefane,
thank you for confirming! Then these are no errors, nut just warnings related to the 3D visualization. You don't need to worry about them if the output looks right.
Cheers,
Lukas
