### ISSUE TITLE
--version argument

### ISSUE THREAD

**Issue by NanBlanc** [3dgeo-heidelberg/helios#255]
**Is your feature request related to a problem? Please describe.**
All of them, as identifying the compiled version will help all debugging works

**Describe the solution you'd like**
a "--version" argument

**Comment by albertoesmp** [comment]
I like this suggestion. Thank you for proposing it. It will be implemented soon!

**Comment by albertoesmp** [comment]
The `--version` argument has been implemented: https://github.com/3dgeo-heidelberg/helios/commit/3666f67e141f76fefb6b424b67be8257b0907dd9
