### ISSUE TITLE
efilepath option for point cloud loader fails when supplying single file

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/helios#26]
As the `efilepath` option is a logical extension to `filepath`, it should also work when supplied a single file path (similar to python's `glob.glob`). Currently, loading fails when a single file (without * or ?) is given as `efilepath`.

**Comment by miguelyermo-heidelberg** [comment]
@lwiniwar 
Could you confirm that this bug is still there? Is working fine for me: loading an .obj by using efilepath works fine on my side

```<param type="string" key="efilepath" value="data/sceneparts/hashing/a.obj" />```

**Comment by han16nah** [comment]
My latest info that it works indeed for the objloader but not for the point cloud loader (xyzloader)

**Comment by miguelyermo-heidelberg** [comment]
Indeed, the logic of the two methods is different. Thanks for pointing it out.

**Comment by miguelyermo-heidelberg** [comment]
@lwiniwar, could you provide me an example where this bug appears?
I tried to load the survey ```data/scenes/voxels/sphere_xyzloader.xml``` using _efilepath_ instead of _filepath_ when loading the scene with id ```sphere_xyzloader_demo```. The debugging process shows me that the paths are being correctly managed, even if a single path is provided.
