### ISSUE TITLE
Documentation of requirements for python scripts (conda-yml)

### ISSUE THREAD

**Issue by han16nah** [3dgeo-heidelberg/helios#32]
We have some python scripts which require packages not included in the Python Standard Library. These should be documented in a [conda environment.yml](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment) file and kept up to date.

Currently, I think these dependencies are:
- numpy
- osgeo/gdal
- open3d (these are used in [pyhelios_demo/helios.py](https://github.com/3dgeo-heidelberg/helios/blob/main/pyhelios_demo/helios.py) bzw. [pyhelios_demo/pyh.obj](https://github.com/3dgeo-heidelberg/helios/blob/main/pyhelios_demo/pyh_obj.py))
- matplotlib 
- polyscope (these are used in [pyhelios_script.py](https://github.com/3dgeo-heidelberg/helios/blob/main/pyhelios_demo/pyhelios_script.py))
- geopandas (used in [extra/flight_planner.py](https://github.com/3dgeo-heidelberg/helios/blob/main/extra/flight_planner.py))

**Comment by lwiniwar** [comment]
fixed by #49
