### ISSUE TITLE
DetailedVoxels wiki entry upgrade

### ISSUE THREAD

**Issue by NanBlanc** [3dgeo-heidelberg/helios#359]
Is it possible to get an upgrade of scene/DetailedVoxels subsection in the wiki ?

I think expanding the explanation of the names in line 6 would be helpful, not just i,j,k,PADBVTotal and transmittance.
If you think this is not mandatory, or too long, maybe just give the reference to : [https://amap-dev.cirad.fr/attachments/download/1499/AMAPVox-1.0.1_userguide.pdf](https://amap-dev.cirad.fr/attachments/download/1499/AMAPVox-1.0.1_userguide.pdf), page 28, to ease information finding.

Can you explain what are the to last attributes per voxel : `attenuation` and `attenuationBiasCorrection`, as they are not mentioned in the userguide of AMAPVox ?  
Also, as you did for line 5, can you precise which ones are actually used by HELIOS++ ?
Thanks a lot, as always :)

**Comment by han16nah** [comment]
Dear Oliver @NanBlanc ,
I updated the Wiki page according to your suggestions: https://github.com/3dgeo-heidelberg/helios/wiki/Scene
Let me know if something is still missing and feel free to close the issue, if you are happy.

I am not sure about the `attenuation` and `attenuationBiasCorrection` either. I assume it's the estimated attenuation coefficient and the attenuation coefficient with a bias correction.

There is some documentation on the attenuation estimators [here](https://doi.org/10.23708/1AJNMP), but it's for version >= 1.8. So I am not sure which estimator (maybe) corresponds to the `attenuation` in previous versions, @philippeverley may be able to help us here :) 

Oliver, are you interested in support for current AMAPVox output files, e.g., version 1.10.4? We could think of writing a separate parser for these if there is the demand for it.
