### ISSUE TITLE
Negative remaining simulation times and completed percentages over 100%.

### ISSUE THREAD

**Issue by miguelyermo-heidelberg** [3dgeo-heidelberg/helios#37]
When executing `./helios data/surveys/toyblocks/uls_toyblocks_survey_scene_combo.xml`, if the `pulseFreq_hz` of each one of the legs is set to 10 000 Hz instead of 100 000 Hz, the first four legs are executed until the 104%, whilst the last one seems to have no end, yielding negative remaining times when the 100% is reached

![Captura de pantalla de 2021-05-18 16-16-09](https://user-images.githubusercontent.com/83340465/118667541-64719280-b7f4-11eb-91d8-1eef24343e97.png)

**Comment by han16nah** [comment]
Could this be the same issue as #22 ?
It is quite a problem.. the copter is only working properly when setting `slowdownEnabled = "false"` (which is not the default).

**Comment by miguelyermo-heidelberg** [comment]
Maybe, but it seems that the behaviour is not the same in both cases (maybe because of the different pulseFreq_hz used). I'll have a look tomorrow.

**Comment by han16nah** [comment]
Any news on this @miguelyermo-heidelberg ?

**Comment by miguelyermo-heidelberg** [comment]
Not yet, I am focusing on other high priority tasks. I'll let you know when I start looking into it.

**Comment by miguelyermo-heidelberg** [comment]
Seems to be fixed in the current dev branch.
