### ISSUE TITLE
Wrong LasSpecification::TRANSMISSION_TOWER label.

### ISSUE THREAD

**Issue by miguelyermo-heidelberg** [3dgeo-heidelberg/helios#38]
LasSpecification.h:70

I know for sure that the classification label of a transmission tower should be 15, but maybe is set to 14 for some reason unknown to me. I just want to know if I should set the right label.

In any case, it seems that these labels are not used in any part of Helios++, for now...

**Comment by lwiniwar** [comment]
Seems like a typo. Please fix it.
See Table 17 on page 30 here: http://www.asprs.org/wp-content/uploads/2019/07/LAS_1_4_r15.pdf

**Comment by han16nah** [comment]
fixed by 70b018e58c1e7dd3f9d9f284577caf3a15aedfc8
