### ISSUE TITLE
How to place the scanner location relative to the scene or loaded 3D model

### ISSUE THREAD

**Issue by thivageran97** [3dgeo-heidelberg/helios#426]
I have an issue to place the scanner at a specific coordinate. I have a 3d model in .obj. how can i place the scanner in specific location where the x and y coordinates are similar to the 3d model. i dont seem to find any tool to have and it seems the scanner location is based on its on coordinate and not relative to the obj. model.

**Comment by lwiniwar** [comment]
Hi @thivageran97 ,

the OBJ model's coordinate system origin is aligned with the HELIOS++ coordinate system's origin, as long as you don't use the `translate` option in your scene XML. So if you open the OBJ file (e.g. with a text editor) and check the coordinates there, this should give you a rough idea where the OBJ's contents are located. You can then either transform this to be close to (0,0,0) in HELIOS++ and place your virtual scanner at (0,0,0), or just place the scanner close to the coordinates you found in the OBJ.

See here for details on how translation, rotation, and scale can be used to transform the OBJ's contents:
https://github.com/3dgeo-heidelberg/helios/wiki/Scene#coordinate-transformations

Cheers,
Lukas
