### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by thivageran97** [3dgeo-heidelberg/helios#490]
Hi, I'm currently using Python version 3.11 to run most of my code and would like to incorporate helios++ simulation as part of my code. The issue currently is I have to run separately on Python version 3.10. Is there a possible support for 3.11 or anything I could change for it to run on python 3.11.

**Comment by han16nah** [comment]
Hi @thivageran97 

We just published HELIOS++ v2.0.0 ([releases](https://github.com/3dgeo-heidelberg/helios/releases)), which supports Python versions 3.9 to 3.13.
Are you running your code in a conda/mamba environment? Then you can simply run
`conda install -c conda-forge helios` to install HELIOS++ to your environment. Hope that helps.

Cheers,
Hannah

**Comment by thivageran97** [comment]
Hi, Yes I did realize that the new version would support all the latest version of Python. At the moment I'm running my script on PyCharm, I guess would need to switch to Conda to make full use of the new release. 

Thank you.

**Comment by bhoefle-3dgeo** [comment]
You can also connect a conda / mamba environment to PyCharm. You just need to change the Python Interpreter in your PyCharm project. Thus, it is not a big change, just installing [mamba](https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html) or [micromamba](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html) and modify your project in PyCharm.

Good luck and fun hacking with Python and HELIOS++

**Comment by thivageran97** [comment]
Yes, that works well after a little tweaking here and there. Thank you.
