### ISSUE TITLE
Scene Parts not loaded when using absolute paths

### ISSUE THREAD

**Issue by JonasWenkHD** [3dgeo-heidelberg/helios#492]
**The problem**

When using absolute paths in your scene xml to reference scene parts, HELIOS++ does not find them and ignores them. The following output is printed: 

"The path "absolute/path/to/the/scene/part.obj" was given.
It leads to the loading of an invalid scene part, which is automatically ignored when composing the scene."

Using an absolute paths works in older HELIOS++  versions. 
Absolute paths also still work when referencing the scene xml in the survey xml.

**Comment by dokempf** [comment]
Is this happening with `v2.0.0` and worked before?
