### ISSUE TITLE
Change logging level of scene loading

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/helios#54]
In reaction to #41 , the output that is generated when loading input files should be changed from `INFO` to `DEBUG`, so that it is shown in `-v2` mode only. 
For users running in default mode, information should instead be provided as
```
Loading sceneparts ...
... 123456 sceneparts loaded (took 4 seconds)
```
(or similar)

**Comment by miguelyermo-heidelberg** [comment]
Included in #53
