### ISSUE TITLE
Empty outputs in some files.

### ISSUE THREAD

**Issue by miguelyermo-heidelberg** [3dgeo-heidelberg/helios#55]
I've noticed that, in the cases where several legs are part of a Scene, the even numbered outputs (leg000_*, leg002_*) contain information about the simulated point cloud and the trajectories of the scanner, whilst the odd numbered outputs are empty. Is this deliberated or it is a bug? I suppose that this is happening because each pair of legs forms a trajectory that the scanner must travel along, but I am not 100% sure.

**Comment by lwiniwar** [comment]
Hi Miguel,
any leg with `active=False` will result in an empty output point cloud file. This behaviour was ported from the java version, I do not oppose to just not write the files. However, I think the names should not change, as the numbering of the legs then 1:1 follows the legs defined in the `survey.xml` file.
Trajectories should still be written even with `active=False` as long as `trajectoryTimeInterval_s` is set to something other than `0` - they might also be interesting to the user at some point, so I'd keep this behaviour.
