### ISSUE TITLE
Add archive function or script to fully document a simulation

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/helios#7]
For publications etc. it would be very useful to have a script or functionality to archive a simulation. Using this functionality, all files and information required to reproduce a simulation would be compiled to a zip archive or similar:

* XML files
* HELIOS binary (incl version information)
* HELIOS source code of the version corresponding to the binary data / sceneparts

Results could be compiled separately by the user.
The functionality might either be included in HELIOS++ itself, or be a separate supplementary Python script (the latter preferred at the moment).

This also goes hand-in-hand with a GUI/HTML interface as mentioned in #4

**Comment by han16nah** [comment]
I tried solving this issue: [archive.py](https://github.com/3dgeo-heidelberg/helios/blob/main/extra/archive.py)
The python script writes a zip-directory, from which the specified survey(s) can be run immediately. If executed from a self-built project, which does not contain a run-folder with all the dependencies, the run-folder is downloaded from GitHub. 
Only tested on Windows.

Usage:
`python extra\archive.py <path-to-survey> <path_to_helios.exe> <path-to-zipped_outfile>`

e.g. `python extra\archive.py data\surveys\toyblocks\als_toyblocks.xml run\helios.exe archive.zip`

A list of surveys may also be provided by passing a txt file (one survey path per line):
`python extra\archive.py survey_list.txt run\helios.exe archive.zip`
