### ISSUE TITLE
missing #include<string> Helios++

### ISSUE THREAD

**Issue by FelixEickeler** [3dgeo-heidelberg/helios#74]
I tried compiling the current version of helios++ within my docker.
If get the following error: 
```
/home/phaethon/helios++/src/assetloading/geometryfilter/WavefrontObjCache.h:12:14: error: ‘string’ in namespace ‘std’ does not name a type
12 | typedef std::string key_type;

```

After adding #include\<string\> to header, WavefrontObjCache.h  it compiles totally fine. Can you please verify and if needed apply the fix ?

**Comment by lwiniwar** [comment]
Hi @FelixEickeler, thanks for your feedback. Yes, `#include <string>` is required for some versions of the C++ libraries, and it is good practice to include it anyhow. I have added it to multiple locations where `std::string` was used but `#include <string>` was missing, I hope I got them all, see commit 4c363a84e5829c4f7e9a4a50a941ef5559c60357

I'll merge it into main after the checks pass.

Best regards,
Lukas
