### ISSUE TITLE
Boost should not force static linking

### ISSUE THREAD

**Issue by copyme** [3dgeo-heidelberg/helios#79]
There should be an option as it is in CGAL for controlling whether boost should use static or dynamic libraries. Not all Linux distributions offer static libraries of boost.

**Comment by albertoesmp** [comment]
First, thank you for opening this issue. I think you are pointing to something that we should really improve for Linux users.

I've tried to solves this by updating our CMake files, so now it is possible to use `-DBOOST_DYNAMIC_LIBS=1` to use boost dynamic libraries when compiling Helios++.  Unfortunately, I couldn't test this on my system yet so I'm not sure if the fix does the trick or if the problem persists. I would really appreciate if you could try this new flag and tell us if it is working or not. In case it is not working, please provide us with both the CMake console output and the log file at _/.../helios/cmake-build-release/CMakeFiles/CMakeOutput.log_ so we can figure out what is going on.

Thank you again for your collaboration!

**Comment by miguelyermo-heidelberg** [comment]
I've tried the proposed solution and I am able to compile helios against both static and dynamic libraries. I would like to do more tests in the distribution you used, @copyme, if you provide me that information. Thank you!
