### ISSUE TITLE
User warnings about unused/misspelled XML-parameters

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/helios#9]
We should improve error handling/user warnings for HELIOS++.

* Per default, only information and errors are reported. This includes which default values are used where no XML parameter was specified. However, unless specifying "-v2", we do not see which parameter is affected and the info is therefore useless.   
We should change `Using default value: 1` to `<ParameterXYZ> - Using default value: 1` or a similar info message which **contains the parameter name**

* It can quickly happen, that your survey does not work as expected if you misspell a parameter. Ideally, we would catch these errors and give a warning to the user. 

To do:
* [x] definition of XSL https://wikipedia.org/wiki/Extensible_Stylesheet_Language
* [ ] based in the XSLs, check XMLs when parsing and give out error messages/warnings

Example XSL for surveys: 
[survey.zip](https://github.com/3dgeo-heidelberg/helios/files/5854638/survey.zip)
can be validated using https://www.freeformatter.com/xml-validator-xsd.html

**Comment by han16nah** [comment]
See [scene.xsd](https://github.com/3dgeo-heidelberg/helios/blob/dev-xsd/extra/scene.xsd) and [survey.xsd](https://github.com/3dgeo-heidelberg/helios/blob/dev-xsd/extra/survey.xsd) for basic XML schema definitions for scenes and surveys.

Can be checked with python, e.g. `xmlschema` ( `pip install xmlschema`) 
```python
import xmlschema

xmlschema.validate(r'..\data\surveys\demo\tls_arbaro_demo.xml', 'survey.xsd')
xmlschema.validate(r'..\data\scenes\demo\arbaro_demo.xml', 'scene.xsd')
```
